### ISSUE TITLE
Cannot run any example!

### ISSUE THREAD

**Issue by Cimbro** [EvergineTeam/Samples#1]
Hi Guys,
we are very interested in a solution like yours , in particular for havign 3d graphics on web.
We are trying to run your example under web (we are interested in webassembly) but without success...

We have this straage message

1>Asset exported: 'C:\Users\danie\Desktop\AreaLightsDemo-main\Content\Models\DamagedHelmet\DamagedHelmet.bin.wefile'
1>Asset exported: 'C:\Users\danie\Desktop\AreaLightsDemo-main\Content\Models\FlightHelmet\FlightHelmet.bin.wefile'
1>EXEC : warning : file packager is creating an asset bundle of 352 MB. this is very large, and browsers might have trouble loading it. See https://hacks.mozilla.org/2015/02/synchronous-execution-and-filesystem-access-in-emscripten/
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error : The Windows Subsystem for Linux dotnet environment may not be properly setup, and you may need to run the environment setup script. Open an Ubuntu WSL shell and run:
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error : 
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error : `wslpath "C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\scripts\dotnet-setup.sh"`
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error : 
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error :
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018: errore imprevisto dell'attività "PackageProjectTask".
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018: System.InvalidOperationException: Failed to setup WSL environment.
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018:    in WaveEngine.Targets.Web.Tasks.PackageProjectTask.ValidateEmscripten() in C:\agent\_work\3\s\src\Targets\Web\WaveEngine.Targets.Web.Tasks\PackageProjectTask.cs:riga 174
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018:    in WaveEngine.Targets.Web.Tasks.PackageProjectTask.Execute() in C:\agent\_work\3\s\src\Targets\Web\WaveEngine.Targets.Web.Tasks\PackageProjectTask.cs:riga 66
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018:    in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018:    in Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Compilazione progetto "AreaLightsDemo.Web.csproj" NON COMPLETATA.

We have last version of visual studio with net5.
Any suggestions?
Regards
D

**Comment by davilovick** [comment]
Hi Cimbro,

In latest WaveEngine previews, when compiling a WebGL adapter, you need to enable Windows Subsystem Linux (WSL) in your machine (I reconmend you to use Ubuntu 18.04 LTS and WSL1). 

In the error output message, it indicates that you need to properly setup the WSL environment to perform Wave Engine compilations.
To solve that problem, you need to open the WSL shell console, and run the specified command (don't forget the \` characters):
\`wslpath "C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\scripts\dotnet-setup.sh"\`

This command will install mono versions, emscripten sdk and other things.
After that, I reconmend you to restart your computer.

Best regards,
David Ávila

**Comment by Cimbro** [comment]
Hi David
I did as you sad but i have same problem. Nothing changed.

Badly im using wsl2 (ubuntu 18.04).
Could be this the issue?
Regards
D

Il gio 4 feb 2021, 12:30 David Ávila <notifications@github.com> ha scritto:

**Comment by Cimbro** [comment]
Any news on that?
I am still stucked!!

Il gio 4 feb 2021, 13:40 Daniele Saretta <dsaretta@gmail.com> ha scritto:

**Comment by DogGodGit** [comment]
"Graphics Tools" feature is missing. Please add "Graphics Tools" feature from Settings/Apps & features/Optional features
