### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by bartengine27** [EvergineTeam/Samples#2]
Dear,

  Where can I find a Blazor sample?

Thanks,
Bart

**Comment by Jorgemagic** [comment]
Hi Bart,

You can check the [Digital-Twin demo](https://github.com/EvergineTeam/DigitalTwin-Demo) where Evergine uses Blazor to run in web.

Thanks,
Jorge

**Comment by rahulsolanki001** [comment]
Hey,
I am trying to make changes in my model imported in evergine web using frontend JS event listeners. I can't seem to figure it out. Pls help me on this.
