### ISSUE TITLE
Hi is Evergine open source?

### ISSUE THREAD

**Issue by Joe23232** [EvergineTeam/Samples#5]
Hi, I know this may be off topic, but  is Evergine open source? If so which license does it use?

**Comment by Jorgemagic** [comment]
Hi Joe,

Evergine is **free to use** but is **not open source**. On the other hand, if you need professional support or access to the source code you can check out the Evergine services [here](https://evergine.com/download/)

**Comment by Joe23232** [comment]
Hi @Jorgemagic 

Thanks for your response. It is kinda a shame that Evergene is not open source but I do appreciate your response.
